try {
    alert('Action completed!');
    data.push(value);
    return a + b;
} catch (error) {
    console.error("Error:", error);
}