try {
    alert('Action completed!');
    return a + b;
    return x - y;
} catch (error) {
    console.error("Error:", error);
}