try {
    return a + b;
    data.push(value);
    alert('Action completed!');
} catch (error) {
    console.error("Error:", error);
}