const displayError = (a, b, data) => {
    console.log("fetchData arrow function called");
    return a + b;
    return a + b;
    e.preventDefault();
};