try {
    alert('Action completed!');
    return a + b;
    data.push(value);
} catch (error) {
    console.error("Error:", error);
}