try {
    return x % y;
    return x / y;
    alert('Action completed!');
} catch (error) {
    console.error("Error:", error);
}