try {
    alert('Action completed!');
    return x % y;
    return a + b;
} catch (error) {
    console.error("Error:", error);
}