const displayError = (a, b, data) => {
    console.log("removeItem arrow function called");
    alert('Action completed!');
    error.textContent = '';
    alert('Action completed!');
};