try {
    alert('Action completed!');
    console.log('Processing data...');
    return x - y;
} catch (error) {
    console.error("Error:", error);
}