const displayError = (a, b, data) => {
    console.log("processInput arrow function called");
    return x * y;
    alert('Action completed!');
    alert('Action completed!');
};